### ISSUE TITLE
Acquire SSL certificates for the public endpoints

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#1038]
**Todo:**
- [x] Get proof of concept working:
  - [x] Azure Function to request certificate
  - [x] Azure Function to serve challenge
- [x] Store ACME challenge and certificate in KeyVault
- [x] Setup path-based routing in Application Gateway to proxy /.well-known/acme-challenge/* to azure function
- [ ] Setup SSL certificate to Application Gateway
  - [x] Programmatically add certificate to AppGW
  - [x] Programatically apply certificate to port 443 and setup routing for that port
  - [x] Redirect HTTP traffic to HTTPs via rules
  - [ ] Retry re-applying cert/rules when AppGW is changed (etag changed)
- [ ] Setup SSL-certificate renewal via time-based function trigger
- [x] Add function environment variables for appgw domainname, email (used by letsencrypt), keyvault address, etc
- [x] Document manual instructions (via az cli)
- [x] Wrap everything in an ARM template for automation
  - [x] top level template
  - [x] virtual network
  - [x] keyvault 
  - [x] application gateway
  - [x] azure functions
- [ ] Integrate into OpenCGA ARM template 

The OpenCGA REST and GRPC services need to have their communications secured by SSL certificates. 

Most likely this will be done by App Gateway (#1023). Given the rest of the solution is automated I think we'll need to dynamically acquire a certificate for the public endpoint and configure it on App Gateway. 

One option for this is using Lets Encrypt but other options may be available.

**Comment by martinpeck** [comment]
@lawrencegripper can you please make sure the title and description reflect the task, and then we can assign elsewhere? Thanks!

**Comment by lawrencegripper** [comment]
@martinpeck I've updated the details and removed the tag.

**Comment by bart-jansen** [comment]
**Todo:**
- [ ] Get proof of concept working without AppGW:
  - [ ] Azure Function to request certificate
  - [x] Azure Function to serve challenge
  - [ ] Azure Function Proxy to route /.well-known/acme-challenge/* to azure function
- [ ] Store private keys and certificate in Blob storage/KeyVault
- [ ] Setup routing in Application Gateway
- [ ] Programmatically add certificate to Application Gateway
- [ ] Setup SSL-certificate renewal via time-based function trigger
- [ ] Wrap everything in an ARM template for automation
	
**Blockers/issues:**
- Need to use Linux based app machines to generate private key as this doesn't seem to be working on windows-based node.
  - Since Linux is in preview proxies don't seem to be working which are required
- Best way to programmatically add SSL cert to Application Gateway

**Comment by martinpeck** [comment]
Ignoring the `/.wellknow` routes, what are the other routes that you'll serve from this function app, and on which domain will they sit?

**Comment by lawrencegripper** [comment]
I believe for the challenge response only the `./.wellknown*` routes are required.

**Comment by bart-jansen** [comment]
Set up repository to track progress at: https://github.com/bart-jansen/automated_appgw_encryption

**Comment by bart-jansen** [comment]
Status update:
- Successfully able to store/retrieve secrets/certificates in KeyVault using Functions (via MSI)
- Successfully able to access the Azure ARM REST API through Functions (via MSI)
- Unable to update the [Application Gateway](https://docs.microsoft.com/en-us/rest/api/application-gateway/applicationgateways/createorupdate) via the REST API. Every PUT request using an existing appgw/RG-name tries to create an AppGW instead of updating the existing one

**Comment by bart-jansen** [comment]
Got the REST API working together with @lawrencegripper and pushed a working Class that deploys the generated SSL-certificate to AppGW: https://github.com/bart-jansen/automated_appgw_encryption/commit/b725f4beed8784b1e354a3ba56e699e7125c9110

**Comment by marrobi** [comment]
Adding 'azure-smoke' label as this will be required for testing with live data.

**Comment by martinpeck** [comment]
suggestion ....

set up App Gateway with a self signed cert, and then have this code replace that cert with a better cert

**Comment by martinpeck** [comment]
should add the App Gateway public endpoint to the base template outputs

**Comment by marrobi** [comment]
Closing as merged.
