### ISSUE TITLE
Enable pagination over samples data

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1210]
It is not a good practice to return variants with large quantity of samples. New studies appear with more than 100k samples. for these studies, we need to enable some sample pagination.

#### QueryParams
 - **sampleLimit** : Limits the number of included samples 
 - **sampleSkip**  : Skips a certain number of included samples 
 
#### VariantQueryResult
In order to manage this pagination, a new fields should be added to the `VariantQueryResult`:
 - **numTotalResults** : to indicate the total number of samples available for the given query
 - **numSamples** : the actual number of samples in the result.

#### Multi studies
When returning multiple studies with samples, the skip/limit should start work across them, as if the samples where sequential.

#### Configuration
Same as with the variants limit, a default and maximum samples limit should be added to the `storage-configuration.yml`

 - **sample.limit.default** : Default sampleLimit
 - **sample.limit.max** :  Maximum sampleLimit

#### Tasks:
- [x] Implement sampleLimit and sampleSkip params
- [x] Add sampleLimit and sampleSkip params to the Swagger and CLI
- [x] Extend VariantQueryResult to include `numSamples` and `numTotalSamples`
- [x] Add default and max sample limit to configuration file
