### ISSUE TITLE
Simplify phoenix SQL when filtering by PopulationFrequency

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1228]
Population frequency is stored in HBase as a length 2 integer array {ref, alt}.
If the value is missing, it's read as 0, so the SQL query to filter by PopulationFrequency < 0.1 is something like:
```sql
SELECT * 
    FROM "table_variants" 
    WHERE 
        "PF_GENOMAD_GENOMES_ALL" IS NOT NULL 
        OR "PF_GENOMAD_GENOMES_ALL"[2] < 0.1 ;
```

This query, when combined with a list of variants, is much slower than expected.

#### Query 2 variants where popFreqAlt is null or less than 1 (current)
```sql
SELECT 
  CHROMOSOME, POSITION, REFERENCE, ALTERNATE, TYPE, A_PF_GNOMAD_GENOMES_ALL
FROM "table_variants" 
WHERE (CHROMOSOME,POSITION,REFERENCE,ALTERNATE) IN (
    ('1',16534,'C','T'), 
    ('1',21319,'G','A')) 
  AND (A_PF_GNOMAD_GENOMES_ALL is null OR A_PF_GNOMAD_GENOMES_ALL[2] < 1);
```
Time: **0.369 seconds**

Removing the "is null" part, the query runs 10 times faster.
Both queries return the same result.

#### Query 2 variants where popFreqAlt is less than 1
```sql
SELECT 
  CHROMOSOME, POSITION, REFERENCE, ALTERNATE, TYPE, A_PF_GNOMAD_GENOMES_ALL
FROM "table_variants" 
WHERE (CHROMOSOME,POSITION,REFERENCE,ALTERNATE) IN (
    ('1',16534,'C','T'), 
    ('1',21319,'G','A')) 
  AND (A_PF_GNOMAD_GENOMES_ALL[2] < 1 );
```
Time: **0.038 seconds**

#### Solution
To effectively remove the "IS NULL" part of the query, and keep the same results, we must ensure that the pop freq column is not null, storing by default an array with `[1,0]` if the value is not present in the annotation.

To avoid increase unnecessary the size of the table, this default values will be only used for the cohorts ALL of each study, and the super populations of the GENOMAD_GENOMES, and 1kG_PHASE3 studies 

#### Tasks
- [x] Add default value for selected pop freqs
- [x] Do not add "OR IS NULL" filter if not needed
- [x] Ensure that filter "OR IS NULL" is not added when filtering by stats

Will require to regenerate the annotation columns. Depends on  #1227

**Comment by j-coll** [comment]
After this change, a query filtering by 3 samples and popFreq that was taking 6s, now takes only 1.7s
