### ISSUE TITLE
Include parents genotype in the SampleIndex

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1244]
The SampleIndex can be used for a large number of queries. The index contains all genotypes but HOM_REF (`0/0`) and MISS (`./.`)
Queries with `GT=0/0` can use the index when filtering also by another sample, and subtracting all the genotypes from the first sample. This mechanism was a good improvement, but still takes from 4 to 10s to find 10 variants.

This type of query is most likely to be executed when filtering by a segregation mode. For example, for a monoallelic segregation, where the father is affected, will query `FATHER:0/1,1/1;MOTHER:0/0;CHILD:0/1,1/1`

#### Store parents genotype
If we store the genotype of the parents in the child index (like we store some annotation), we could resolve this query reading only the query of the child.

For each variant we can store a byte, using 4 bits to encode the genotype of each parent:

| Code | GT |
|---|---|
| 0 | `0/0` |
| 1| `0/1` |
| 2| `1/1` |
| 3  | `0\|0` |
| 4 | `0\|1` |
| 5 | `1\|0` |
| 6 | `1\|1` |
| 7 |  `0` |
| 8 |  `1` |
| 9 |  multi allelic hom |
| A |  multi allelic het |
| B |  missing hom `./.` |
| C |  missing het `./0`, `./1` ... |
| D | unknown |
| E |  |
| F |  |

#### Filter by parent genotype
The parents of the sample can be registered into the metadata.
Given a query, there'll be a list of accepted genotypes. If a parent was requested to be `0/1`, `0|1` or `1|0`, the index should be 1, 4 or 5. If we have an array `boolean[16]` that is true only in the positions 1, 4 and 5, we can easily check, given the stored genotype code, if the parent had the required genotype:

```
boolean filter(boolean[16] filter, byte genotypeCode, boolean firstParent) {
    
    parentGenotypeCode = firstParent ? genotypeCode : genotypeCode >>> 4;
    return filter[ genotypeCode & 0x0F ]
    
}
```

The boolean[16] can be replaced with a `char`, which has 16 bits

#### Tasks
- [x] GenotypeCodec
- [x] Generate new column in MendelianErrorDriver
   - [x] Rename MendelianErrorDriver to FamilyIndexDriver
- [x] Add parents filter to SampleIndexQuery
- [x] Filter by parents filter in converter
