### ISSUE TITLE
Add Biotype+Ct combination to SampleIndex

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1364]
When filters Biotype and ConsequenceType are used in a query, they must match within the same transcript of the variant (see #1214)

This combination of params is quite often, and should be fully supported by the SampleIndex. Supporting this will reduce the filtering in hbase/phoenix, and allow exact counts using only the SampleIndex.

### How to represent the valid combinations:
Each non-intergenic variant will have a set of pairs <CT, BT>, which defines a list of CT and BT values. This can be represented as a matrix where the rows are CT values in the variant, the columns are BT values, and the intersection is a boolean representing if that specific combination occurs in the variant. 

| - | bt1 | bt2 | ... |
|---|---|---|---|
| **ct1** | ct1-bt1 | ct1-bt2 |   | 
| **ct2** | ct2+bt1 | ct2+bt2 |  | 
| **...** |  |   | ... | 

This matrix can be stored sequentially, using one bit per boolean.

Then, to read the matrix, first has to determine its size, by counting the number of unique CT and BT in the index (see `Integer.bitCount()`). Then, the order of the rows and columns should match with the order of the bits within the index.

#### Example
A varant with 3 transcripts:

| Transcript | BT | CT |
| --- | --- | --- |
|T1| protein_coding |                 missense_variant |
|T2| processed_transcript    |        stop_lost |
|T3| protein_coding       |           frameshift_variant, missense_variant |

This will generate the biotype index entry `0b10001000` and the ct index entry `0b0000000001000011`. With this we can create the matrix of combinations:

| - | protein_coding (bit 7) | processed_transcript (bit 3) |
| --- | --- | --- |
| **missense_variant (bit 0)** | 1 | 0 | 
| **frameshift_vairant (bit 1)** | 1 | 0 |
| **stop_lost (bit 6)** | 0  | 1 |

Storing this matrix sequentially only uses 6 bits : `10 10 01 `, or `01 10 10` depending on writing in bit or little endian.

### Pitfalls
 - As the size of the matrix depends on the number of CT and BT, when using this new array `CT_BT` for filtering, we must determine the size of the matrix of each non-intergenic variant (regardless of the result of any other filter) to keep track of the position in the array.
   - What about with the Mendelian Errors? This is specially hard to do when reading MendelianError variants from the SampleIndex, as the variants cursor is "jumping".

### Tasks
- [x] Implement utility classes BitOutputStream and BitInputStream
- [x] Create and store new array
- [x] Use the new CT_BT array to filter. 
- [x] Ensure MendelianError variants are correctly filtered with this new array. <strike>Otherwise, disable this feature when filtering by MendelianError.</strike>
