### ISSUE TITLE
Implement VariantStats OpenCGA Analysis

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1376]
Currently the VariantStats are considered an internal storage operation. We need an Analysis to allow users compute stats over any set of samples, given any input query. 

## Tasks
- [ ] Implement Analysis
- [ ] Implement default executor using OpenCGA-Storage API
- [ ] Implement HBase MapReduce executor
- [ ] Implement MongoDB Local executor
