### ISSUE TITLE
Move StorageManagers to opencga-analysis

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1407]
The division between StorageManager and StorageEngine is clear. These managers can be moved to opencga-analysis.

Some operations can be migrated to use the new AnalysisFramework.

### Tasks
- [x] Move code to opencga-analysis
- [x] The dependency of Catalog from Storage is not needed anymore. Revert #435
- [x] Implement `variant index` using the AnalysisFramework
- [x] Implement `variant stats` using the AnalysisFramework
- [x] Implement `variant export` using the AnalysisFramework
- [x] Remove StudyInfo and FileInfo
- [x] Do not copy generated files into catalog from storage operations
