### ISSUE TITLE
Transform endpoint analysis/variants/sample/query into an Analysis

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1435]
This operation was build in #536. It finds, given a set of variants, the list of samples that have any or all mutations from the list.

This functionality may take a long time to compute if the list of variants or samples is large. Also, limiting these parameters could make the method not useful.

Therefore, we should transform this method into an asynchronous analysis.

### Tasks
- [ ] Rename endpoint `analysis/variant/sample/query` to `analysis/variant/sample/run`
- [ ] Extract the functionality into an analysis of the OpenCGA Analysis Framework
- [ ] Implement one default AnalysisExecutor iterating directly the list of variants
- [ ] Implement an specific AnalysisExecutor for HBase
