### ISSUE TITLE
Add SAMPLE_ID and FILE_IDX to StudyEntry::format

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1436]
When adding the new endpoint `analysis/variant/sample/data` at #1230, we created a new ad-hoc model called `VariantSampleData` for this. Then, the `VariantStats` were added in #1286. This model ended up being just a shuffled `StudyEntry` with two differences: 

1. Samples are grouped by genotype
2. Each sample contains its `sampleId` and its `fileId`

The first difference mainly developed for IVA. This should not be part of the model. Also, this is no longer a requirement of IVA.

The second difference could be added easily to the existing `StudyEntry` by extending FORMAT field with two special FORMAT fields: 
- `SAMPLE_ID` with the sample ID
- `FILE_IDX` with the 0-based  position of the file in the list of _files_.

By adding these new format fields, we could deprecate the ad-hoc model `VariantSampleData` and use the standard `Variant` model.

We could also allow adding these format entries to the general variants query methods using the `includeFormat` parameter. Example: `includeFormat=GT,SAMPLE_ID` `includeFormat=all,FILE_ID,SAMPLE_ID`

### Tasks
- [x] Allow adding `SAMPLE_ID` and `FILE_IDX` to the format
- [x] Replace `VariantSampleData` with `Variant`
- [x] Rename `/variant/sample/data` with `/variant/sample/query`
