### ISSUE TITLE
Implement a new functionality to load demo data

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#1472]
It would be great to have a public demo for people to test and prepare scripts

**Datasets**
The proposed datasets to be loaded are:

- 1000G Phase 3
- UK10k
- Illumina platinum
- Corpasome
- CEPH Trio
- Cancer

**Projects and Studies**
TBD

**Tasks**
- [ ] Add demo configuration files
- [ ] Implement a Demo manager to read the configuration and load the demo
- [ ] Add a new command to _opencga-admin.sh_ to load the demo
