### ISSUE TITLE
Tool to copy VariantStats into PopulationFrequencies

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1473]
There is a strong relationship between the PopulationFrequencies from the annotation and the VariantStats. Actually, the frequencies that CellBase provides with the annotation were once VariantStats from an OpenCga installation (see http://hgva.opencb.org)

The VariantStats can be currently exported as PopulationFerquency objects to be imported directly into CellBase. By doing this step directly on OpenCGA, reading the VairantStats, transforming them into PopulationFrequencies, and updating the database, we could then export the entry variants database and import as the variation table from CellBase.

This functionality can be implemented as one Tool with multiple executors.

### Tasks
- [ ] Implement HBase executor 
- [ ] Implement MongoDB executor
- [ ] Add tool to clients and cli

**Comment by j-coll** [comment]
Implemented at #1602
