### ISSUE TITLE
Add awarness of the sequencing method when calculating VariantStats

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1503]
Each sequencing methods covers a different genomic area. These could be "whole genome", "exome", some commercial or custom panels, or even MicroArrays.

Being aware of the sequencing method is important in studies where multiple methods are mixed when calculating VariantStats, in order to calculate the Frequency of a certain variant.

The frequency of a variant is obtained by dividing the number of alternate alleles and the total number non-missing of alleles.
This total number of alleles will depend on the number of samples that were sequenced in each specific region/variant.
To have this information, we need to be able to determine, for each variant, how many samples where sequenced in that area. Samples not sequenced in a specific area will be seen as "missing genotypes", so these will not count to the total number of alleles.

## File Experiment
File experiment (https://github.com/opencb/opencga/issues/1494) has been improved with some new fields to include the sequencing method and a way to determine the list of regions/variants sequenced in that file.

## Implementation details
In the case of having a study that mixed files from different sequencing methods, we need to know, when calculating stats, for each variant, in which sequencing methods it was present.
As the number of regions/variants of each sequencing method can be really large, it is not reasonable to have this information in memory and check, for each variant, in which methods were present.
Instead, we can run a preparation step where this information is loaded as an extra column/field in each variant. Then, the VariantStatsCalculation only needs to read one extra column/field.

## Tasks
- [ ] Determine the format of the regions/variants of each experiment
- [ ] Improve storage metadata:
  - Add `experiment` to `FileMetadata`
  - Add `samplesPerExperiment` to `CohortMetadata`
- [ ] Implement preparation step in storage-mongodb
- [ ] Implement preparation step in storage-hadoop
- [ ] Improve VariantStatsCalculator
