### ISSUE TITLE
Allow indexing multiple files per sample in StorageHadoop

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1542]
## Overview
The current storage engine forbids to load two files from the same sample. Usually, this is not an issue, where there is only one file per sample, but there are some exceptions that can be divided into two categories:

- **Split-data** - non-overlapping/disjoint files
  - **Horizontal split**: The first exception was for datasets where the data is split horizontally, i.e. per chromosome or per region. This is easy to solve, as the regions are not overlapping, so there will be no duplications or discrepancies. See #696, #1471
- **Multi-file** - overlapping/interspersed files
  - **Multiple VCF callers per variant type**: In this scenario, different VCF callers will be used for each type of variants, SNV, INDEL, SV... This case is similar to the horizontal split, as these variants should not overlap, but as they could overlap, it required special considerations.
  - **Different sequencing method for the same sample**: In some clinical scenarios, a sample may want to be confirmed by using either a different VCF caller, or repeating the whole sequencing with a different method, but with the same sample.

## Duplications and Discrepancies
- **Duplication**: A sample has the same variant with the same genotype in two or more files
- **Discrepancy**: A sample has the same variant with the different genotypes in two or more files

The main issue of loading multiple files per sample is how to handle the duplications (same genotype in two files) and discrepancies. These can be handled in two different ways:
### Return multiple sample entries
The easiest way is to have different entries in the for each sample, depending on the file source. This is especially useful when the analyst is executing a comparison between two VCF callers
### Return duplications/discrepancies as IssueEntries
When the duplications are not expected because each file was for a different Variant Type, or when the sample duplications are expected, but not relevant, these can be returned as IssueEntries. See  https://github.com/opencb/biodata/issues/177

### Calculate stats
....
### Sample aggregation
This feature is incompatible with the Aggregation operation. This may be allowed in future versions.
### Mendelian Errors calculation
In case of having a discrepancy, the mendelian errors will be computed for each genotype combination.
### Combination
Split-data and multi-file load can not be combined, as each category will make incompatible assumptions.
### Concurrent load
....
### Variant query
If `includeFile` (either explicit or implicit) is present, include only sample data from that specific file.

### Sample Metadata
We need to keep a List of loaded fileIds in a strict order.
Also need to specify in which scenario
### Variants table
**Requirements:**
 - ...

### Sample index
**Requirements:**
 - Handle duplications/discrepancies
 - Allow filtering by file index of each file of the sample
 - Allow filtering by certain files of a sample
 - Ensure count is still correct, even if there are duplicated variants

To match the requirements we need to add a few more fields to the FileIndex field. The size of the index will increase from 1byte to 2bytes per variant (type `short`).

| Pos | Size | Field |
|----|------|-----|
|  0  |  1 |  Multi-file variant duplication - Indicate that the next entry refers to the same variant | 
|  1  |  4 |  File IDX - file index to the file loading position, relative to the sample | 
|  5  |  3 |  TYPE | 
|  8  |  1 |  PASS/NO_PASS | 
|  9  |  2  | QUAL  | 
|  11 | 3 |  DP - Increase from 2 to 3 bits - [5,10,15,20,25,30,40] | 
|  14 | 1 | Unused | 
|  15 | 1 | Unused | 

Issue #1471 implements the ability to rebuild the SampleIndex while loading when loading split data by type, which is a special scenario of the multi-file load. 

#### Ensure correct count
To avoid counting the same variant twice from different genotypes (discrepancy), we need to  store a new counter with the number of discrepancies.

### Params
```
  --load-split-data  [REGION , CHROMOSOME]
  --load-multi-file
```

## Requires
- https://github.com/opencb/biodata/issues/177

## Tasks
- [x] Improve load/rebuild sample index to include new fields
- [ ] Improve SampleIndex Map Reduce operation to add new fields
- [ ] Fix sample index queries
  - [ ] Fix sample index queries for MendelianError iterator
- [ ] Ensure count from sample index works fine with discrepancies
- [ ] Ensure fileIdx correctness
- [ ] Fix variants table queries
  - [ ] Ensure that with include-file include samples from that specific file
- [ ] Add concurrent load limitations
- [ ] Add new load params
- [ ] Tests
- [ ] Confluence
- [ ] ...
