### ISSUE TITLE
Extend sample fitler

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#1567]
There are two different variant sample filters: _genotype_ and _sample_. They are similar and incompatibles what makes them a little bit tricky to use. These two parameters could easily be merged into one single parameter called _sample_ by extending this with _genotype_ features. This extension will keep backward compatibility.

## Current status
_genotype_ filter accepts the following syntax:
   
    genotype=sampleA:0/1;sampleB:0/1;sampleC:1/1
    genotype=sampleA:HET;sampleB:HET;sampleC:HOM_ALT

While _sample_ filter accepts only sample IDs with no genotypes:

    sample=sampleA;sampleB;sampleC

When using _sample_ filter this is translated internally to genotype filter using HET and HOM_ALT. In both filters `,` and `;` are allowed for OR and AND respectively.

## Merge with _genotype_ Proposal
Both filters could easily merge together into _sample_ filter by allowing (optionally) writing the genotypes, all these are valid examples:

    sample=sampleA;sampleB;sampleC
    sample=sampleA:0/1;sampleB:0/1;sampleC:1/1
    sample=sampleA:HET;sampleB:HET;sampleC:HOM_ALT

Basically, _sample_ **keeps** current functionality and allows _genotype_ syntax.

## Family Extension
_sample_ filter can be extended even further to support family-related filters. When filtering by recessive, compound heterozygous or de Novo you have to define a family in Catalog and use filters _family_ and _familySegregation_. This requirement should not necessary, we can easily extend _sample_ to support the following queries:

    sample=sampleA:RECESSIVE
    sample=sampleA:DE_NOVO

In this case, **only** one sample is allowed and Catalog must define the father and mother of the sample.

## Summary
With all these improvements sample filter can have 4 different forms:

1. Just a list of sample IDs (current):

    sample=sampleA;sampleB;sampleC

2. Samples with genotypes:

    sample=sampleA:0/1;sampleB:0/1;sampleC:1/1
    sample=sampleA:HET;sampleB:HET;sampleC:HOM_ALT

3. Filter by mode if inheritance (recessive, dominant, X-linked, ...), only **one** sample is allowed. This sample must have just one disorder and a father and/or mother in Catalog.

    sample=sampleA:RECESSIVE

4. Filter by segregation (compound heterozygous, de novo, mendelian error), only **one** sample is allowed. This sample must have a father and/or mother in Catalog. No disorder is required

    sample=DE_NOVO

## Tasks

- [ ] merge _genotype_ with _sample_ 
- [ ] allow mode of inheritance
- [ ] allow segregations mode
