### ISSUE TITLE
Remove files from variants storage

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#192]
Currently it's not possible to delete specific samples data. Issue extracted from issue #160 

Deleting samples data can be implemented by removing specific samples, or removing indexed files.

- Delete files
    A file contains a set of samples. The storage metadata contains a list of all the indexed samples. Also, delete BatchFileOperations are available.
- Delete samples
    This feature will require more accurate metadata information, to be able to know exactly which samples are indexed. Now the only way to determine if a sample is indexed or not, is if its file is indexed.
    **Deleting samples is out of the scope**

**Task list:**

- [x] Remove `delete` methods from `VariantDBAdaptor` interface
- [x] Rename `delete` and `drop` methods with `remove`
- [x] Delete file for MongoDB
   - [x] Collect all existing genotypes
   - [x] Synchronize delete with the stage collection
   - <strike> Detect and remove unused secondary alternates </strike>
   - [x] Add BatchFileOperation blocking the study to avoid concurrent operations. 
   - [x] Migration script to collect loaded genotypes
- [x] Delete file for Hadoop
- [x] Invalidate cohorts stats with removed samples 
- [x] Remove deleted samples from cohort ALL. 
      Be aware that samples can be in multiple files.
- [x] Add Remove operations at VariantStorageManager

**Comment by j-coll** [comment]
see first approach [drop_file.js](https://gist.github.com/j-coll/747d3e9f73267f49ca19d3c8f0b58c58)

**Comment by j-coll** [comment]
Migrate script for MongoDB at https://gist.github.com/j-coll/3dec01abc70644943d33de78105c633e
