### ISSUE TITLE
Add direct loader for the first file in a chromosome to load directly to the variants collection

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#354]
Skip the stage collection for the first file in a chromosome. This can speed up a lot some loads.

Related with #288 

#### When to use it:
- First loaded file in study:
  - There is no other indexed file
  - There is no staged file

- First loaded file in region:
  - There are some loaded file
  - All loaded files, and the file to load, have the same samples
  - `--load-split-data` is provided

#### Tasks:
 - [x] Create direct loader that fills `stage` and `variants` collections.
 - [x] Decide if a file should be loaded directly
    - [x] First file ever
    - [x] First file in region (split data)
 - [x] Execute direct load instead of stage+merge
 - [x] Parallelize bson conversion
 - [x] Ensure duplicated variants detection
