### ISSUE TITLE
New Storage Variant filters

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#494]
There are a bunch of new filters for Variants. This will be an umbrella issue for all the new issues in this release.

- [x] FILTER #442
- [x] Make `annot-xref` filter more clever. Accept variant id, cosmic, clinvar and protein values. #502
- [x] Match Consequence type with the specified Gene filter (if any) #500
- [x] Accept return keys "all" and "none" #542 
- [x] Automatic "RETURNED_*" if missing #546
- [x] Negative genotype filter #489
- [x] Filter by sample annotation #541
- [x] SAMPLES : Variants where some samples are present (not missing or reference. With the main alternate) #543 

Let's keep this list updated. Please, add in comments more filter suggestions 

Other filters to add in the future:

- Returned Cohorts #485
- COHORT: Variants were some samples from cohort are present (not missing or reference. With the main alternate)
- Include formats: Format fields to return (GT, AD, DP, all, none, ...)
- Contains (or not) RS id (from dbSnp)
- Improve variant filters name. Consistent naming policy.
- Update documentation with new filters
