### ISSUE TITLE
Major ACL improvements

### ISSUE THREAD

**Issue by pfurio** [opencb/opencga#634]
The usage of ACL's in Catalog has been really useful for OpenCGA. However, important issues have been detected like the one described in #628. In order to fix those issues, important changes need to be done that will affect the internal implementation. Things that will be done are:

- [x] Deprecate acl from the data models. They will be stored internally in a different way to be able to make faster queries. #632 
- [x] Another related and important aspect would be supporting multiple groups per user. The set of rules established will need to take into account this new multigroup feature. #633 
- [x] Change current implementation of how entries are fetched. In order to support pagination in queries, we will need to add ACLs as part of the queries so the rules will be applied by every dbAdaptor in this case instead of the managers for performance purposes. #628 
- [x] Add new internal _members_ group. #642
