### ISSUE TITLE
Clean catalog deprecated code

### ISSUE THREAD

**Issue by pfurio** [opencb/opencga#667]
Over time, some methods and classes have been deprecated and we just need to make sure they are not being called anymore and we can easily remove them, On the other hand, some classes might be moved to other packages. An example of this are the data models which should be in the core package and not in catalog.

Additionally we should:
- [x] Make catalogManager a factory of managers #668
- [x] Remove interfaces from catalog managers #669
- [x] Check authentication token is present in all the manager methods. #670
