### ISSUE TITLE
Make use of the new VariantMetadata model from Biodata

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#673]
The new VariantMetadata model is meant to be the standard and unified model to contain all the metadata for variants. It is a multi-study model, which matches perfectly with the multi-study concept of the Variant storage engine.

**Related:**
- opencb/biodata#151
- opencb/opencga#690

**Tasks:**
- [x] Create VariantMetadata when exporting variants
  - [x] Convert StudyConfiguration to VariantDatasetMetadata
  - [x] Individuals must be in the same order as samples in samples data
  - [x] Include specific file header and file statistics
  - [x] Enrich with Catalog metadata
- [x] Read new VariantMetadata when importing variants
- [x] Replace intermediate metadata file from transformation
- [x] Remove deprecated VariantSource.Aggregation.
- [x] Remove deprecated StudyType.
- [x] Create a webservice endpoint `analysis/variant/metadata` to get the new `VariantMetadata` object
  - [x] Use this `VariantMetadata` to convert to VCF at client
- [x] Use VariantFileHeader to store aggregated header information in StudyConfiguration
