### ISSUE TITLE
Admin migration command line 

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#690]
More frequently than we would like, with new releases, we introduce changes to the data model, database schema and configuration files.

To allow upgrading the opencga version, we implement some migration scripts, but they are highly error prone and require many manual steps.

To ease the upgrading process, a new migration command will be needed in the admin command line.

```
opencga-admin.sh migration v1.2.0
                       ... v1.3.0
                       ... v1.4.0
```

The command line is not intended to have the migration commands for all the existing versions. Old migration scripts won't be added.

**Suggested libraries for mongodb migration:**
  - https://github.com/mongobee/mongobee
  - https://github.com/mongeez/mongeez (stale)

**Tasks:**
 - [x] Create command structure at opencga-admin.sh
 - [x] Add storage migration code for #673
   - [x] Transformed intermediate files
   - [x] VariantSource at Catalog (`files.attributes.variantSource`)
   - [x] VariantGlobalStats at Catalog (`files.stats.variantStats`)
   - [x] VariantStudyMetadata to VariantFileHeader at StudyConfiguration
   - [x] VariantSource at VariantSoruceDBAdaptor
