### ISSUE TITLE
Store info fields on storage-hadoop

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#704]
At ticket #602 a new column per sample was added to include other genotype fields from the format.

That approach had this properties:
1. One column per sample
2. Phoenix type `VARCHAR ARRAY` with one FORMAT value per element
3. Only FORMAT fields stored
4. Fixed size and positional array --> Allow filtering
5. One optional array entry for secondary alternates, at the end of the array.

With that approach, we can not store other INFO fields, or modify the list of fields to store. 
Creating a new column with file information to store QUAL, FILTER and INFO fields,  we allow to store all the information available in the original vcf.

The optional element for secondary alternates will be moved to the new column. This will allow to store secondary alternates from aggregated files, and store more FORMAT fields to the sample column if needed.
It may happen that this new column is not returned. In that case, the secondary alternates will be missing.

The new column will be a Phoenix Array. The first 4 elements are fixed (CALL, ALTS, QUAL, FILTER), and the rest are INFO fields. The order of the INFO fields will be shared among all files. If any field is missing, a null value will be written in that array position.
 - `[CALL, ALTS, QUAL, FILTER, INFO_1, INFO_2, ..., INFO_n]`

For each variant, this INFO field should be stored if:
- The variant does not have any sample (aggregated file)
- The variant does not have genotype information
- The variant has any sample where the genotype is not the _"default genotype"_ (default genotype is typically `0/0`)

**Tasks:**
- [x] Fill this new column in the converters
- [x] Define and register in phoenix the new column (basic and advanced)
- [x] By default, all FORMAT fields should be stored
- [x] Ensure QueryParam INCLUDE_FORMATS is not broken
- [x] Add filter by FILTER
- [x] Add filter by FILES
- [x] Add include/exclude "files"
- Add new tests:
  - [x] Load multi sample files
  - [x] Load somatic files (no genotypes)
  - [x] Calculate aggregated statistics
  - [x] FILE and FILTER queries

**Questions:**
- Aggregated column with `ComplexFilter` is redundant. Should we remove it?
