### ISSUE TITLE
Accept enriched genotypes at GENOTYPE filter.

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#750]
Genotype filter accepts a list of genotypes per sample. Querying multi-allelic genotypes is not always as easy, because there are multiple combinations that depends on the number of secondary alternates (0/1, 0/2, 1/2, 3/5, ...)

This operation can be pretty easy. Since #192, a list with all the loaded genotypes is stored and updated in the StudyConfiguration.

##### Option A
We can allow wildcards (`*`) as "any allele **different** than **0** or **missing**". Example:
 - `0/*` -> `0/1` , `0/2` , `0/3` ... `0/n` 
 - `1/*` -> `1/1` , `1/2` , `1/3` ... `1/n` 
 - `*/*` -> `1/1` , `1/2` , `2/2` ... 

##### Option B
An alternative can be accept an `n` instead instead of a wildcard `*` but with the same meaning:
- `0/n`
- `n/n`

##### Option C
There is also other alternate to accept genotype aliases, which will help with polyploidy and phased genotypes:
- `HOM_REF` -> `0`, `0/0`, `0/0/0`, ...
- `HOM_ALT` -> `1`, `1/1`, `1|1`, `2/2`, `3/3`, `1/1/1`, ...
- `HET` -> `0/1`, `1/2`, `0/2`, `2/4`, `0|1`, `1|0`, `0/0/1`, ...
- `HET_REF` -> `0/1`, `0/2`, `0/3`, `0|1`, ...
- `HET_ALT` -> `1/2`, `1/3`, `2/4`, `2|1`, ...
- `MIS` -> `.`, `./.`, `././.`, ...

#### Conclusion
We will go for **Option C**, as is the most flexible solution

#### Tasks
 - [x] Define genotype classes
 - [x] Allow new genotypes in storage-mongodb
 - [x] Allow new genotypes in storage-hadoop
 - [x] Add tests
 - [x] Improve documentation to add new accepted values

**Comment by imedina** [comment]
Nice, let's implement the * for now.

**Comment by jpflorido** [comment]
Although it shouldn't be a problem, be aware that GATK represents spanning deletions as * 
https://gatkforums.broadinstitute.org/gatk/discussion/6926/spanning-or-overlapping-deletions-allele

**Comment by imedina** [comment]
That should be a problem (in theory), @j-coll actually the two options to implement are:

 - `0/*` -> `0/1` , `0/2` , `0/3` ... `0/n` 
 - `*/*` -> `1/1` , `1/2` , `2/2` ... 

`1/*` would be part of `*/*`

**Comment by j-coll** [comment]
Implementing **Option C** with new genotypes `HOM_REF`, `HOM_ALT`, `HET`, `HET_REF`, `HET_ALT` and `MISS`
