### ISSUE TITLE
Fill missing genotypes operation for all samples from a study in the Variant storage

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#757]
`fill-gaps` operation implemented in  #713 was planned to fill all the "gaps" in variants present in any of the given samples. 

Executing this operation against all the samples in the database can be really expensive in terms of time and disk usage, because it will fill all the gaps in the spare matrix that the variants table is. To save some disk space, this operation could skip all the samples where the genotype is homozygous reference (HOM_REF, 0/0), and files where all the samples are HOM_REF.

So, this operation will fill all the gaps where the value is a missing variant, or an overlapping variant.

#### Implementation details

- Unlike the fill-gaps operation (#713), this operation will be only available for studies with merge=BASIC
- Because this operation is most likely going to read all the data in the archive table, the input for the MapReduce job should be the archive table.
   - <strike>To avoid OutOfMemoryError, rows from archive should be read in batches</strike>
   As variants from archive table are distributed in batches, this is not longer needed. See #777 
- The resulting table should look like a table loaded with `merge=ADVANCED`, but without the list of genotypes 
- Later executions of this operation will check again all the samples that were HOM_REF in variants already processed by previous executions, and, finally, doing nothing, because they are HOM_REF. Some kind of mark should be left to mark that certain samples in that variant were already processed, so in every execution, only **new variants** and **new samples in every variant** are processed.
  - This mark will also help to know if a gap on sample data is an unknown genotype (?/?) or a HOM_REF genotype (0/0)

#### Tasks

- [x] Decide integration with #713 
- [x] Implement MR task reading from archive table
- [x] Add some kind of "mark" for processed variants
   Mark the whole study configuration as `missing_genotypes_updated=true`
- [x] Return correct genotype depending on the mark

#### Future Tasks
 - Add a "mark" per variant for processed variants

**Comment by imedina** [comment]
This would potentially avoid the need to have two loading modes: _basic_ and _advanced_. The default could be the current _basic_ and the _advanced_ could be executed at any moment.
