### ISSUE TITLE
Support and load BREAKENDS in Variant Storage

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#760]
BREAKENDS are a really complex feature from VCF specification that allows an arbitrary rearrangement event. 

> An arbitrary rearrangement event can be summarized as a set of novel adjacencies.  Each adjacency ties together 2 breakends. The two breakends at either end of a novel adjacency are called mates.
> 
>There is one line of VCF (i.e. one record) for each of the two breakends in a novel adjacency. 
> [1]

Despite most of the information contained in both mates is redundant, we want all the information contained in all mates. Also, the annotation is potentially different for each of the mates. 

We want to store all the information, and be able to query for any breakend of the adjacency.

In most of the situations the variant caller will only be able to provide a pair of breakends conforming a novel adjacency, unable to relate this with any other pair of breakends. But in simpler scenarios, the caller hay be able to relate pairs of breakends describing more complex rearrangement events. In this case, a field EVENT will be added to the column INFO.

We can find a list of known chromosomal rearrangements in the book Modern Genetic Analysis [2] and Wikipedia [3].
Types of events (this list may not be exhaustive):
 - Balanced
   - Reciprocal Translocations
   - Inversion
 - Unbalanced
   - Insertion
   - Deletions
   - Duplications (tandem, CNV,...)

Determining the type of event is out of the scope, and can be a further action. No extra processing will be done with the EVENT value.

### Model representation
There are some information specific to breakend variants. This information is available the alternate of the VCF, but it has to be parsed and placed in the proper fields of the Variant model.

The new information available is:
- breakend orientation 
- breakend mate location 
  - chromosome 
  - position 
  - cipos
- breakend insertion sequence (optional)

#### Orientation
There are 4 possible junction orientations, depending on how that breakend is connected with the mate. The VCF specification does not provide any naming policy for this orientations, so we have to define our own names.

An initial idea is specify, for the BND and its mate, if the junction is made to the right to left of the position. 

| REF | ALT | meaning | Orientation type | 
| ---- | ----- | ------ | ------ |
| s |   t[p[  |  piece extending to the right of p is joined after t | RL (Right -> Left) |
| s |   t]p]  |  reverse comp piece extending left of p is joined after t | RR (Right -> Right) |
| s |   ]p]t  |  piece extending to the left of p is joined before t | LR (Left -> Right) |
| s |   [p[t  |  reverse comp piece extending right of p is joined before t | LL (Left -> Left) |

#### Proposals
Given this variant from a VCF, it could be modelled in different ways:
```
chr1  .  10  A  ATT[chr11:200[
```

a) Flat model

```js
{
  chromosome :  "1",
  start : 10,
  reference : "A",
  alternate : "ATT[11:200["
  type : "BREAKEND"
  sv : {
    type : "BREAKEND_RL",
    bndInsSeq : "TT",  // Left A is removed, as is not part of the insertion
    bndMateChromosome : "11",
    bndMateStart : 200,
    bndMateCiStartRight : 4,
    bndMateCiStartLeft : 5,
  }
}
```

b) Nested model

```js
{
  chromosome :  "1",
  start : 10,
  reference : "A",
  alternate : "ATT[11:200["
  type : "BREAKEND"
  sv : {
    type : "BREAKEND_RL",
    bnd : {
      insSeq : "TT",  // Left A is removed, as is not part of the insertion
      mate : {
        chromosome : "11",
        start : 200,
        ciStartRight : 4,
        ciStartLeft : 5,
      }
    }
  }
}
```

#### Final model:

```js
{
  chromosome :  "1",
  start : 10,
  reference : "A",
  alternate : "ATT[11:200["
  type : "BREAKEND"
  sv : {
    type : null,
    breakend : {
      insSeq : "TT",  // Left A is removed, as is not part of the insertion
      orientation : "RL",
      mate : {
        chromosome : "11",
        position : 200,
        ciPositionLeft : 4,
        ciPositionRight : 5,
      }
    }
  }
}
```

### Normalization
Another point to deal is the normalization. Should we normalize these variants? If so, how?

Normalizing the previous variant is easy:
`chr1   10  A  ATT[chr11:200[`   -->  `1:11:-:TT[11:200[`, where the reference, in the variant model, is an empty string.

But, in case of not having an insertion sequence, we may remove the context base at the alternate, loosing the information regarding the junction orientation.

Having the variant `chr9:100:A:A[chr10:300[` , it can be normalized in different ways:

```js
// Do not leave empty alleles for BND
{ chromosome: "9" , start : "100" , reference : "A" , alternate : "A[11:104474477[" }
// Leave empty reference allele, increase start, and remove context base from alternate, as the orientation information is available in "sv.type"
{ chromosome: "9" , start : "101" , reference : "" , alternate : "[11:104474477[" }
// Same as before, but leave a "-"  to indicate the orientation of the junction
{ chromosome: "9" , start : "101" , reference : "" , alternate : "-[11:104474477[" }
// Same as before, but leave a "."  to indicate the orientation of the junction. See VCFv4.3 5.4.5 Telomeres
{ chromosome: "9" , start : "101" , reference : "" , alternate : ".[11:104474477[" }
```
#### Final normalization:
Leave a dot "`.`" to indicate the orientation of the junction.
`chr1   350  A  A[chr11:200[`   -->  `1:351:-:.[11:200[` (increase 1 the start position)
`chr1   250  A  [chr11:200[A`   -->  `1:250:-:[11:200[.` (do not increase the start position)

### Tasks
- [x] Add breakend representation to Variants model
- [x] Normalize breakend variants
- [x] Store and recover BREAKEND variants in MongoDB.
- [x] Document breakend variants in [Structiral Variants](http://docs.opencb.org/display/opencga/Structural+Variants)

### Notes
[1] [VCF specification v4.3](https://samtools.github.io/hts-specs/VCFv4.3.pdf)
[2] [Modern Genetic Analysis. Chromosomal Rearrangements](https://www.ncbi.nlm.nih.gov/books/NBK21367/)
[3] [Chromosome abnormality](https://en.wikipedia.org/wiki/Chromosome_abnormality#Structural_abnormalities)
