### ISSUE TITLE
Error indexing file existing file with the same name.

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#768]
Having multiple files registered in Catalog with the same name (but in different folders) is not a problem from the catalog point of view, and should not be for storage.

### Issue:

1. Register two vcf files (or more) in catalog with the same name (different paths, different ids...)
1. Index the first (not last) registered file.
1. The file is indexed using the fileId of the last registered file
1. NullPointerException updating index status.

### Details:
The StudyConfiguration has a map from fileName to fileId. 
When adding all the VCF files to this map, the files  with same fileName overwrite the previous fileId, storing only the last registered file.
The input to the VariantStorageEngine are the URIs. It reads the fileId from the StudyConfiguration, which may be wrong.

### Solution:
The StudyConfiguration should only contain indexed files, or files to be indexed.
When updating the StudyConfiguration with information from Catalog, not all files should be added to the files map. Only those to be indexed.

### Tasks:
- [x] Add failing tests confirming the error
- [x] Add only the files to be indexed to the StudyConfiguration
- [x] Ensure `FileManager#matchUpVariantFiles` handles correctly having multiple files with the same name.
