### ISSUE TITLE
Split archive table in file batches

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#777]
The current design of the Archive table adds each new file as a new column, using the same set of row keys. This is against the HBase philosophy, which prefers to grow vertically, rather than horizontally.

This change will definitely break the merge=advanced feature. This is not an issue, since with merge=basic and fill-missing operation, we can obtain the same result as with merge=advanced.  

#### Questions
 - Distribute VariantFileMetadata column in batches too? 
  Move to metadata table. See #781

#### Tasks
- [x] Replace new archive RowKey
- [x] New pre-split strategy with expected number of files (orientator number)
- [x] Adapt fill-gaps to new archive schema
- [ ] Document new archive schema

#### Subtasks:
- Remove merge=advanced mode #796
- Adapt remove file to new archive schema #800 

#### Other tasks.
- Use private storage file ids, instead of ids from catalog.
- Rename archive table to match with variants table name plus a sufix
- Split variants from archive in REF and NON_REF #
- Remove archive load from MapReduce
