### ISSUE TITLE
Split VcfSlice from archive table in REF and NON_REF columns

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#778]
The operation fill-missings only needs the NON_REF variants, as it skips REF blocks.

Grouping variants in two categories (REF and NON_REF) will speed up that operation, reducing the bytes to read from archive table.

Columns:
 - `<FID>_N` with NON_REF variants
 - `<FID>_R` with REF_ONLY variants

#### Tasks:
 - [x] Divide variants in two put operations
 - [x] What about metadata column
  - Do not modify the VariantFileMetadata column name. Use the fileId as is : `<FID>`
 - [x] What about archive load by MR? Non-direct archive load
    - Archive load by MR is disabled

#### Related with:
 - #777
 - #757
