### ISSUE TITLE
Filter out overlapping files in variants in storage-hadoop

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#779]
From #549:

> It may happen that some FileEntry present in a Variant were only overlapping that variant, and not actually in that variant.
> 
> For example:
> 
> |Variant | File_1 | File_2 |
> |----------|---------|----------|
> | chr1:1000:A:C | ✔️ |     |
> | chr1:1000:A:T |      | ✔️ |
>
> .....

This problem was sorted out for storage-mongodb. By that time, it was not a problem in storage-hadoop since the data stored in hbase was limited (only GT and FILTER). All the remaining data was added in #602 and #704. 

In order to handle the overlapping files, we have to add some kind of mark to indicate that the file was overlapping that variant. The solution for mongo was to negate the fileId of the file in the overlapping variant.

In storage-hadoop we have two options:

1. Store the overlapping file information in a different column. This won't increase the number of columns in hbase, but will increase the columns in phoenix, creating larger SQL statements. This can be problematic after loading too many files.
1. Add one field to the file column (as it's an array) to indicate if that position was overlapping or not. The current structure is  `[CALL, ALTS, QUAL, FILTER, INFO_1, INFO_2, ..., INFO_n]`. It can be added at any position before the INFO values, as the size may increase. This will require to change the file filter from "`<FILE_ID>_F is not null`" to "`<FILE_ID>_F[2] is 'NON_OVERLAPPING'`", which will check that the column exists, is not null, and the value of the second field  in the array is the corresponding (position and value are an example)
1. Same as above, but add the new field as an INFO element. This will require to define it in the header.

#### Questions:
 - [x] How should we mark the variants?
   - Create an enum with 3 types of overlapping status: VARIANT, REFERENCE, NONE.
   Add to each file cell the corresponding value.
   - Add a new element in the file array as the third element. Displace rest of elements.
 - [x] Should we mark also as "NON_OVERLAPPING" the overlaps with "ref-block" variants?
   - Mark overlaps with "ref-block" with VariantOverlappingStatus.REFERENCE

#### Tasks:
- [x] Include new element to FILE column
- [x] Modify fill-gaps/fill-missing to mark variants as "NON_OVERLAPPING"
- [x] Filter using this new element
