### ISSUE TITLE
Move storage-hadoop metadata to a separated table

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#781]
Metadata is being stored as special rows in archive and variants tables. This causes some issues, and requires extra checks to skip those rows.

This tables should be moved to a separated table.

#### Schema
 - StudyConfiguration
    
    | RowKey | type | value | lock |
    |----|----|----|----|
    | `S_<STUDY_ID>` | 'STUDY_CONFIGURATION' | json.gz |  LOCK |
    
 - List of studies
    
    | RowKey | type | value | lock |
    |----|----|----|----|
    | `'studies'` | 'STUDIES' | json Map<String, Number> |  LOCK |
    
    
 - VariantFileMetadata
    
    | RowKey | type | value | static | lock |
    |----|----|----|----|----|
    | `S_<STUDY_ID>_F_<FILE_ID>` | 'VARIANT_FILE_METADATA' | json.gz | STATUS | LOCK |
    
    
 - <strike> List of loaded files per study </strike>
    

#### Tasks
- [x] Change HBaseStudyConfigurationDBAdaptor implementation
- [x] Change HBaseVariantFileMetadataDBAdaptor implementation 
- [x] Think about list of loaded files. Is it needed?
    Replace by a scan where "status" column is "READY"
