### ISSUE TITLE
Fill missing prepare step: copy variants to fill into archive table

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#793]
After adding some time counters in the FillMissing process, we realize that a significant among of time was taken by querying the Variants table in order to get the variants to fill. This step was not needed before splitting the archive table into file batches.

Executing a MapReduce to calculate stats on a small cohort (which reads all variants) takes approximately 10minutes.

It's reasonable to think that a MapReduce job that reads all the variants (from a study) and writes them into the archive table won't take much more than 10min.

With this information, we don't need to query the Variants table, as we already have the information in the Archve table.

#### Implementation details:
A new MapReduce will read all the variants from a study, and write the variants in the archive table.
 - First, it will discover how many file batches are present 
 - For each variant, it will detect to which VcfSlice belongs
 - Will emit one `Put` mutation per variant per file batch, having no value and a column like:
    `_V_<POS>_<REF>_<ALT>`

#### Tasks:
 - [x] Create a MapReduce job to prepare FillMissing
 - [x] Change the "scan" over the Archive Table to include columns starting by "`_V`"
 - [x] Do not query Variants table to get variants to fill.

#### Related with:
 - #757 
 - #777

**Comment by j-coll** [comment]
With a dataset of 1600 files divided in 7 file batches, the new prepare step took 00:09:40, and made an improvement of 01:16:00
