### ISSUE TITLE
Remove merge=advanced from storage-hadoop

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#796]
After splitting the archive table in file batches (#777), we are not longer able to execute the index pipeline with the advanced merge mode (i.e. use a MR job to merge files from archive and load the variants table)

The new mechanism for loading files and the fill-missing operation can produce the same result as the advanced merge, being a much more scalable solution.

We should remove all the code related with the advanced merge.

#### Tasks:
 - [x] Remove `_V` columns from archive table.
 - [x] Remove merge=advanced related columns from variants table
 - [x] Rename `<STUDY_ID>_0/0` column to `<STUDY_ID>_ST`
