### ISSUE TITLE
Mark already processed variants in fill missing operation

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#803]
Every time that the operation fill-missing is executed, all the files for all the variants are processed, repeating all the processing done in previous executions. This operation won't scale. We need to minimize the number variants and files processed:
 - New variants: Need to process all files for this variants
 - Already processed variant: Only process new files

We need to add a _mark_ to each variant, to know which files have been processed. 
We know that the list of _indexed files_ from study configuration is sorted. Writing the id of the latest loaded file, we will know the list of the previously indexed files up to that point.

In the preparation step, if the variant has the mark, we only need to put the `_V` in those file batches containing a file to update. Also, the value of this cell can contain the mark itself, to discard files already processed.

#### Implementation details:
 - In preparation step, read the column "`_<STUDY_ID>_FM`" that contains the last indexed file
   - If empty, PUT the variant into every file batch
   - Otherwise, PUT the variant only to the modified file batches after the last indexed file.

   This will cause that old file batches will only have new variants. To avoid reading old variants in the next step, we need to write modifying the timestamp.

- In FillMissing step, will read the rows (slice) that have any `_V` column with the latest timestamp.
   - If there were no new variant in the slice, the slice won't be read
   - New variants will need to read information regarding all the files
   - Partially processed variants will only need to read information of new files

#### Tasks:
 - [x] Mark for each variant the latest fileId processed.
 - [x] Improve the fill-missing prepare step to write the `_V` in the required file batches.
 - [x] Return correct unknown genotype depending on the mark. [0/0 or ?/?]
 - [x] Mark in the StudyConfiguration the range of files already processed.
 - [x] Test what if the last updated file is deleted
 - [x] Option to execute a fill-missing on all variants (i.e. ignore this mark)
