### ISSUE TITLE
 Add filter by QUAL in Storage Variants

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#809]
Add a new VariantQueryParam for filtering by QUAL tag, from the original VCF file.

It should work as a numeric filter.

#### Tasks:
- [x] Include the filter to storage-mongodb
   ```json
    { "studies" : { "$elemMatch" : { "files.fid" : 12877, "$and" : [{ 
        "files" : { "$elemMatch" : { "fid" : 12877, "attrs.QUAL" : { "$lt" : 50.0 } } } 
    }] } } }
   ```

- [x] Include the filter to storage-hadoop
   ```sql
    SELECT CHROMOSOME,POSITION,REFERENCE,ALTERNATE,TYPE,"1_ST","1_12877_F","1_12877_S",A_FULL 
        FROM "opencga_variants_test_variants" 
        WHERE ( ("1_12877_F"[3] = 'N' AND ( TO_NUMBER("1_12877_F"[4]) > 50.0 ) ) );
   ```
 
- [x] Add `qual` parameter to rest API and CLI
   - `variant query --file 12877 --qual '<50'`
   - `analysis/variant/query?file=12877&qual=<50`

**Comment by imedina** [comment]
How will the new filter be called?  I guess the obvious answer is _**qual**_, right?

**Comment by j-coll** [comment]
That's the idea
