### ISSUE TITLE
Move hbase write step to a sepparated MR for fill-missing operation

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#815]
#### Proposed steps for _Fill missing_:
 1. Prepare variants to fill. Read variants table, write into archive table
 1. Process fill-missings. Read archive table, write in an intermediate file
 1. Write result. Read intermediate file, write in variants table

#### Alternatives:
 1. Instead of an intermediate file, write in the archive table. Same or different column family?
 2. Instead of _SequenceFileAsBinary(Output|Input)Format_, what about loading directly generating an HFile with _HFileOutputFormat2_?

#### Tasks
- [x] Create separated step for writing into hbase
- [x] Define intermediate file. 
    Use _SequenceFileAsBinary(Output|Input)Format_
    Name it as : `fill_missing_<studyId>.bin`

##### Configuration
- [x] Limit num mappers writing into hbase to `1.5*num_nodes`, where 1.5 is configurable
    See [MAPREDUCE-5583](https://issues.apache.org/jira/browse/MAPREDUCE-5583)
    Configure the writers factor with `fill_missing.write.mappers.limit.factor`. By default, 1.5
 - [x] Disable speculative map `mapreduce.map.speculative`
 - [x] Call to "context.progress" to indicate that the mapper is still alive
