### ISSUE TITLE
Create a ProjectMetadata object for Variant Storage

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#832]
There are some information shared between all the studies within the same database in Variant Storage, such as "species", "assembly" or "release", and there may be many other new shared information such us "SearchIndexStatus" or the version of the VariantAnnotation.

This information is being replicated across all the StudyConfiguration, being even possible to have mismatching values.

We should have this information centralized in one single document "_to rule them all_"

#### New global metadata
 - Species & assembly
 - Current release
 - General attributes section

##### Example:
``` js
{
  "species" : "hsapiens",
  "assembly" : "GRCh38",
  "release" : 4,
  "attributes" : {
    "other" : "values"
  }
}
```
#### Tasks:
- [x] Create abstract `ProjectMetadataDBAdaptor`
  - [x] Extend `MongoDBProjectMetadataDBAdaptor`
  - [x] Extend `HBaseProjectMetadataDBAdaptor`
- [x] Change reading species and assembly fom `studyConfiguragion.attributes` to this new object
- [x] Centralize all storage metadata operations in `StudyConfigurationManager`
- [x] Create a `VariantStorageDBAdaptorFactory` to ease construction
- [x] Ensure retro compatibility
