### ISSUE TITLE
Index Sample Genotypes in HBase

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#838]
Thanks to Solr we can query by any annotation in HBase in subsecond time. But Solr can now help when querying with filters of GENOTYPE, SAMPLE or FILE. 

#### Single column scan
We have tried within #826 to speed-up this queries with _Single column scan_ strategy, accessing only the column of this specific sample, which initially may have as much cells as variants has the sample (approx 4M for whole genome). The idea is to reduce the number of rows to filter from hbase with phoenix. This strategy has two problems:

1. After executing the fill-missing operation, the sample column will have a lot of extra cells, one for each variant with missing genotype. The number of cells may increase from 4M to 70M, increasing the number of rows to filter. This could be solved splitting the column into different column by genotype.
1. The time of scanning a single column, despite being much faster than a whole table scan, is not fast enough for real time queries.

We need a different approach.

#### Samples genotype index table

We need a more direct method to get the list of variants from a sample with a certain genotype. The idea is to create a table where the RowKey is the "SampleID + region", the ColumnQualifier is the genotype, and the Value is a list with all the variants. 

The name of this table will be `<db-name>_sample_index_<study-id>`, with SNAPPY compression, and without pre-splitting.

This table should be populated while loading each file. Optionally, a MR operation may exist to rebuild the table _a posteriori_.

Queries to this table should accept a single sample, an optional list of regions, and an optional list of genotypes. 

The HadoopVariantStorageEngine should always decide to use this mechanism if the query:
 - Contains filter GENOTYPE with AND between samples, where at least one filter does not have:
   - Negated genotypes
   - Genotypes `0/0` or `./.`
 - Contains filter SAMPLE
 - Contains filter FILE with AND between files, and at least one of them is single sample.

##### Schema definition

- RowKey =  `<SAMPLE_ID><CHR>\x00<POS / 1.000.000>` , where SMAPLE_ID and POS are written in binary. e.g. `\x80\x00\x00\x09` `1` `\x00` `\x80\x00\x00\x00` 
- Genotype cells:
   - Column = `<GENOTYPE>`
   - Value = `<VAR_1>,...,<VAR_n>`
- Pending variant cells:
   - Column = `_V_<VAR>_<GT>`
   - Value = `[]`
- Genotype count cells:
   - Column = `_C_<GT>`
   - Value = `<GT_COUNT>` in binary

#### Synchronize after fill-gaps or fill-missing

It is true that, after executing any of these operations, there may be new genotypes for the samples.
We need to synchronize the sample index table.

##### Strategies:
1. Update index while writing the results
  This will require either to write execute an APPEND, which may end up with many duplicated data, so, an extra MR job to "clean" duplicated variants may be needed. The genotype counts will need to be recalculated too. Problem: APPEND and INCREMENT hbase mutations can not be executed from a MapReduce.

1. Write new variants in a separated column (or column family) and merge with the other values in an extra consolidation MapReduce. 
   - Every PUT from the fill-missing operation with non_missing genotype without the main alternate (2/3, 2/2, 3/4,...) creates a new PUT in the sample index table, a new cell with column `_V_<GT>_<VARIANT>`
   - A consolidation MapReduce job will scan those affected samples (some samples for the fill-gaps operation, or all samples for fill-missing), reading the rows with any column starting with `_V_`
   - The Mapper will merge the `_V_` columns with the existing values (if any), update the genotype counters, and remove the `_V_` columns.

1. Rebuild the whole index every time.

We'll implement the second strategy.

#### Remove
When removing files, we have to remove also the belonging samples from the index.
Removing a study is easier. Just have to remove the whole table.

#### Restrictions

 - This method does not work (at least, without special effort) with query operator OR
 - File filter will work only for single sample files.

#### Tasks

- [x] Implement SampleIndexLoader
- [x] Implement MapReduce to create index table
  - [x] Add combine step to reduce network transfer
- [x] Implement SampleIndexDBAdaptor
- [x] Implement heuristic for querying using this index
  - [x] With SAMPLE filter
  - [x] With GENOTYPE filter : Only non ref or non missing genotypes only, with AND operator
  - <del> With FILE filter : Only single sample files. What if the file has samples with HOM_REF genotypes?</del>
     - Use FILE filter with this index is out of the scope.
- [x] Define sample index table name
- [x] Define table compression / pre-split
- [x] Enable ApproximateCount
  - [x] Improve with genotype count column
- [x] Handle files without genotypes
- [x] Store list of loaded genotypes
- [x] What should we do with new genotypes loaded during fill-missing and fill-gaps?
  - [x] Implement SampleIndexConsolidate strategy
- [x] Remove samples from index when removing files
