### ISSUE TITLE
Allow numeric operators '<<' and '>>' in Variant Storage

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#847]
Currently, the supported operators for the numerical values in Variant Storage are `<`, `<=`, `>`, `>=`, `=`, `==` and `!=`. 

All this operators implies that **the value exists, and matches the given condition**.

The only exception to that rule is for the Population Frequency. Since f5a3c80aa9f62201a34fd08efd038a92292c84f4, the operators `<` and `<=` applied to PopulationFrequency values also include those variants without that population frequency value, meaning that the default value for a frequency is 0.

This behaviour does not apply to stats filters, as there are not supposed to be missing values, like in PopulationFrequencies.

The proposal is to include 4 new operators that will also include variants where that value does not exist:
`<<`, `<<=`, `>>`, `>>=`

#### Tasks:
- [x] Allow new operators in MongoDB
- [x] Allow new operators in Hadoop
- [x] Allow new operators in Solr
- [x] Improve tests to include new scenarios
  - [x] Protein substitution scores
  - [x] Conservation scores
  - [x] Functional Scores
  - [x] Population frequencies
  - [x] Stats
  - [x] Qual
- [ ] Modify documentation to include new operators
