### ISSUE TITLE
Untie internal Catalog and Storage IDs

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#859]
The storage module has been using internally the same identifiers as catalog for the shared entities like studies, files, ...

Untying this identifiers will reduce the need of synchronizing models, and allow to evolve and match specific requirements.

#### Considerations
This will require a global monotonically increasing id generator for Storage.

#### Depends on:
 - #861

#### Tasks:
 - [x] Create a monotonically increasing id
 - [x] Deprecate accepting user defined IDs (like `--file-id` or `--study-id` when indexing new files)
 - [x] Simplify `CatalogStudyConfigurationFactory` to synchronize only file status
 - [x] Modify `VariantCatalogQueryUtils#parseQuery` to remove internal catalog ids from the queries 
 - [x] Ensure backwards compatibility. Add counter values to ProjectMetadata
 - [x] Do not return internal file id within `FileEntry`

**Comment by j-coll** [comment]
New task:

- [ ] Do not return internal file id within `FileEntry`
