### ISSUE TITLE
Add new filters for INFO and FORMAT fields other than GT

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#863]
#### API

| PARAM | VALUE | EXAMPLE
|---|---|---|
| format  | `[<SAMPLE>:]<FORMAT><OP><VALUE>`  |  `HG00096:GQ>5`  |
| info  |   `[<FILE>:]<INFO><OP><VALUE>` |  `file1.vcf:DP>5`  |

##### Multiple values
This two filters will allow multiple values separated by AND (;) and OR (,). e.g.

- `format` = `HG00096:GQ>5,HG00097:GQ>8`  
  Variants where sample HG00096 has GQ > 5 OR sample HG00097 has GT > 8
- `format` = `HG00096:GQ>5;HG00096:DP>20`  
  Variants where sample HG00096 has GQ > 5 and DP > 20
- `info` = `file1.vcf:DE_NOVO=true;file1.vcf:QD>0.5`  
  Variants where file `file1.vcf` has flag DE_NOVO and has QD > 0.5

##### Optional file and sample
File and Sample are optional. 
- In case of not specifying the file in the `info` param, values from the param `file` will be used instead.
- In case of not specifying the sample in the `format` param, values from the param `sample` or `genotype` will be used instead.

File and Sample must be either present or missing in all the values of the param. 

Wrong combinations:
- `format` = `DP>8,HG00096:GQ>5`
- `info` = `AN>8;file1.vcf:DE_NOVO=true`

##### Filter GT using `format`
It is possible to filter by genotype using the param `format`, instead of the specific param `genotype`. These methods can not be mixed in the same query.
e.g.

 - `format` = `HG00096:GT=0/1,1/1;HG00097:GT=1/1` 
  `genotype` = `HG00096:0/1,1/1;HG00097:1/1`
 - `format` = `HG00096:GT=0/0,0/1,HG00097:GT=0/1` 
  `genotype` = `HG00096:0/0,0/1,HG00097:0/1`

#### Tasks
 - [x] Add new VariantQueryParams and param description
 - [x] Add method to parse the new filter
    - [x] Extract GENOTYPE from FORMAT filter
    - [x] Automatic INCLUDE_FILE and INCLUDE_SAMPLE from INFO and FORMAT filters 
    - [x] Force INFO logical operator match with FILE filter (if any)
    - [x] Force FORMAT logical operator match with GENOTYPE/SAMPLE filter (if any)
 - [x]  Add filters to **opencga-storage-mongodb**
 - [x]  Add filters to **opencga-storage-hadoop**
 - [x]  Add filters to **opencga-storage-search**
 - [x] Add filters to command line
 - [x] Add filters to swagger WS
 - [x] Add tests
 - [x] Add new filters to the [documentation](http://docs.opencb.org/display/opencga/Querying+Variant+Data)
