### ISSUE TITLE
Use variants SampleIndex when reading from MapReduce

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#868]
Genotype indexes are implemented in #838 , and among with #862, provides real time filtering for multiple samples. 

Unfortunately, this behaviour is only available when reading directly from HBase, and not when reading from MapReduce.

To have this feature in MapReduce, we should extend the `TableInputFormat` from hbase in order to implement a new `TableRecordReader` that, given an `InputSplit`, queries first to the index using the `SampleIndexDBAdaptor` and builds `n` GET operations to the variants table. 

#### Tasks:
- [ ] Implement new `TableInputFormat` and `TableRecordReader`
- [ ] Determine when to use the new InputFormat
- [ ] Analyse performance improvements
