### ISSUE TITLE
New Variant query filter "clinicalSignificance"

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#872]
Clinical significance can be found at the VariantAnnotation.

#### Tasks:
 - [x] Add filter for opencga-storage-mongodb
 - [x] Add filter for opencga-storage-hadoop
 - [x] Add filter for opencga-storage-search
 - [x] Add filter to command line
 - [x] Add filter to swagger WS
