### ISSUE TITLE
Handle pending scenarios and rename fill-gaps operation.

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#877]
There are some scenarios where the fill-gaps (and fill-missing) operation is skipping, and should be completed.

#### Pending scenarios

1. Gap found in archive. 
  It may happen that the original file had a region non covered by the file. This situation is normal in VCFs, but really uncommon in gVCFs. Currently, the FillGapsTask is not writing anything. This is then understood as HOM_REF (0/0). In this scenario we should write `?/?` to represent that the information at this locus is unknown.
2. Multiple overlaps
    This scenario consists in having multiple overlapping positions in one variant. This may happen because of many reasons:
      - Deletion from sample A overlapping with N smaller variants from sample B
      - Inconsistent input VCF with overlapping variants

    In this scenario, we shold mark that there is something in this position, but we can not determine what. For this, we can use the special allele  `<NON_REF>` from GATK or `<*>` from the VCF spec v4.3
3. Structural variants
  We should not try to merge structural variants with other smaller variants.

#### Rename operation
After some deliberation, we decided that this operations should be called "aggregate" and "aggregate-famliy" . Therefore, command and internal classes should be renamed to match with this new names.

#### Tasks

- [ ] Write unknown genotype `?/?` when gaps are found in the archive file
- [ ] Use the NON_REF allele for multiple overlappings.
- [ ] Ensure structural variants are not being merged
- [ ] Rename operation
