### ISSUE TITLE
Do not store list of unknown genotypes [?/?] in mongodb

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#895]
#### Tasks
 - [x]  Do not store the list of unknown genotypes `?/?`
 - [x]  Do not use ever `?/?` as defaultGenotype. Small migration required.
 - [x]  Improve `DocumentToSamplesConverter` to determine if a sample is `defaultGenotype` or "?/?" depending on if its file is loaded or not.
 - [x]  Make sure that `files.fid` is always being returned from mongo when returning genotypes.
 - [x]  Ensure GENOTYPES query is not affected by these changes
        Do not skip filter. Improve #641
