### ISSUE TITLE
Optionally exclude some fields from the HOM_REF blocks

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#913]
Currently, we are storing in the archive table all the information from the variants that are reference blocks with HOM_REF genotype. This information represents, approximately between a 66% and a 90% of the original gVCF. So, reducing this part may have a big impact on the final size of the archive table.

It may happen that, for some installations, the analyst does not really need all the data from those blocks. 

The proposed feature is to exclude some fields from those reference blocks. With a new parameter, when loading a file you would be able to load only the specified fields. Example:

```
-D opencga.archive.fields=QUAL,INFO:DP,FORMAT:GT,AD,DP
```
The above will only include the QUAL, the DP from the file attributes, the GT, AD and DP from the SampleData

### Questions
  - Should we force to always load GT, FILTER and QUAL? **yes**

### Tasks
- [x] Modify the converter to only include certain fields
- [x] Add the new parameter in opencga-storage-hadoop
   - [x] Accept keyword `all`
   - [x] Accept keyword `none`
