### ISSUE TITLE
Optionally exclude some fields to load in variant storage

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#920]
Currently, the variant index API accepts a param to specify the fields from the FORMAT should be included in the load.

```
Usage:   opencga.sh variant index [options]
Options:
      --include-extra-fields     STRING            Index including other FORMAT fields. Use "all", "none", or CSV with the fields to load. [all]
```

We should extend this field to all INFO and FORMAT fields, with a similar syntax as for #913
Genotype, QUAL and FILTER should be always included. Genotype can only be excluded with param `--exclude-genotype`

```
Usage:   opencga.sh variant index [options]
Options:
      --include-fields           STRING            Specify which fields from the variant model include during the indexation. ...   [all]
```

#### Tasks
 - [ ] Generic parser for FIELDS option.
 - **storage-mongodb**
 - [ ] Extend include-fields to include/exclude file fields (INFO)
 - **storage-hadoop**
 - [ ] Extend include-fields to include/exclude file fields (INFO)
 - [ ] Ensure aggregate operations make use of this field
 - **Command line**
 - [ ] Add parameter `--include-fields` with new syntax
 - [ ] Deprecate and hide `--include-extra-fields`. Fill `--include-fields` automatically, and log.warn the deprecated param.
