### ISSUE TITLE
Map FILTER values to shorter values 

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#922]
In the VCF, the FILTER column is a list of string values for each variant. The possible filter values are pre-defined in the header.

We could safe some space in the database by mapping the filters to shorter names.

#### Example:

Mapping table:

| FILTER | Mapping |
|----|----|
| PASS | 0 |
| LowGQ | 1 |
| LowDP | 2 |
| LowHetDP | 3 |

Mapping lists of filters:

| FILTER | Mapping |
|----|----|
| LowGQ;LowDP | 1;2 |
| LowHetDP;LowDP;LowGQ | 2;3;1 |

#### Tasks
 - [ ] Store the filter mapping in the StudyConfiguration
 - [ ] Apply the mapping when loading 
    - [ ] storage-mongodb
    - [ ] storage-hadoop
 - [ ] Modify the query builder to query by the mapped values
 - [ ] Handle filter values missing in the VCF header
     -  Ensure we have all the FILTER values during the transform?
 - [ ] Ensure retro-compatibility
