### ISSUE TITLE
OpenCGA Storage Benchmark Implementation 

### ISSUE THREAD

**Issue by wbari** [opencb/opencga#924]
As OpenCGA is contentiously developed, operational and requires an effective way to evaluate the performance of system between different versions as well as installations. The proposed implementation of OpenCGA benchmark will allow not only users to compare and verify system performance but also for developers, a  way to develop a quality software, improve performance and automatically test different combinations to make OpenCGA a bug free system.
 
JMeter is proposed to implement this benchmark using JMeter Java API, as JMeter is a renowned industry tool for performance testing and benchmarks.

The proposed implementation of OpenCGA Benchmark would consists of the following two execution modes:

1: Compare the results of a fix set of queries executed against different OpenCGA version/installations. This will allow developers to measure the impact of the changes in a set of well known queries.
2: Compare the behaviour of OpenCGA with random set of queries against same/different OpenCGA versions/installations. This will allow to explore and measure performance under a more realistic scenario.

Initially only OpenCGA REST web services will be used, by doing this REST and permission overload will be taken into account, avoiding a too optimistic result.

### Fixed Queries Benchmark

A fixed set of queries are defined in a YAML file. Jackson's will read YAML file into Java Bean and then using JMeter Java API executed against the desired storage engine. 

#### Configuration YAML file
``` yml
---
baseQuery :
  summary : true
 exclude : studies

queries :
- id : "RegionAndBiotype"
  description : "Purpose of this query"
  query :
    region : "22:16052853-16054112"
    gene :   "BRCA2"
    biotype : "coding"
    populationFrequencyMaf : "1kG_phase3:ALL>0.1"
  tolerationThreshold : 300

- id : "PF"
  description : "Purpose of this query"
  query :
    populationFrequencyMaf : "1kG_phase3:ALL>=0.2"
  tolerationThreshold : 600
....
sessionIds :
- ""
```

### Random Queries Benchmark

User will be able to configure its desired set of parameters (JMeter Generators), ranges to generate queries. These configurations will be defined in YAML file, read and converted to Java Beans to generate random set of queries based on configuration defined in this file.

#### Random query syntax
...

#### Configuration YAML file
``` yml
---
baseQuery :
  summary : true
  exclude : studies

regions :
  - chromosome : "1"
    start : 10000
    end : 249250621
  - chromosome : "1"
    start : 10000
    end : 249250621
  - chromosome : "22"
    start : 16052853
    end : 16054112

gene :
  - "ZNF566"

ct :
  - "missense_variant"
  - "SO:0001578"

type :
  - "SV"
  - "CNV"

study :
  - "1kG_phase3"

file :
  - "10_input"

sample :
  - "GermlineSample"

filter :
  - "PASS"
  - "LowGQX"

biotype :
  - "protein_coding"

transcriptionFlags :
  - "CCDS"
  - "basic"

xref :
  - "HPO"

drug :
  - "Neto"

clinicalSignificance :
  - "likely_benign"

functionalScore :
  - id : "cadd_raw"
    min : 0
    max : 1
  - id : "cadd_scaled"
    min : -10
    max : 40

populationFrequencies :
  - id : "1kG_phase3:ALL"
    min : 0
    max : 0.2
  - id : "1kG_phase3:AFR"
    min : 0
    max : 0.15

proteinSubstitution :
  - id : "polyphen"
    min : 0.1
    max : 0.9
    operators : [">", "<"]
  - id : "sift"
    min : 0.1
    max : 0.9

qual :
  id : "polyphen"
  min : 1
  max : 9
  operators : [">"]

conservation :
  id : "phylop"
  min : 0
  max : 1
  operators : ["=", "!="]
....
sessionIds :
  - ""
```
### Results
- [x] Define how to show the results
 Benchmark will produce the JMeter report which can be used to generate dashboard. The minimum there must be : 
 1. Executed Query ( With Params)
 2. Elapsed Time
 3. Successful 

### Connectors
The following execution connectors (Samplers) will be supported :

1.  Direct (Direct data access from MongoDB using MongoDBAdaptors)
2.  REST with Permission Verification
3.  REST without Permission
4.  GPRS ( Place holder for next version)

### How to Execute Benchmark

A CLI will implementation will allow user to run OpenCGA benchmark. The CLI will allow to set the following arguments:

1. Connector Type  (Execution Plugin Direct / REST etc)
2. Concurrent Users
3. Execution Mode ( Fixed / Random) 
   1.  All Queries (Deafult)
   2.  Query ID To Execute ( e.g; `-q "RegionAndBiotype"`)
4. Number of Repetitions For Each Query
5. Delay (Query Delay Between Each Execution Among Same Thread)
6. 

.....

### Tasks
 - **Fixed mode**
 - [x] Create FixedQuery Bean
 - [x] Create the new fixed mode
 - **Random query generation mode**
 - [x] Create DynamicQuery Bean
 - [x] Read the new configuration file
 - **Samplers**
- [x] Allow REST sampler work with main `opencga-server` REST
  - [x] Add sessionId
- [ ] Add a GRPC sampler
 - **CLI**
 - [x] Modify Storage CLI With New Options (mode etc)
 - [x] Add file option to command line
- **Report**
- [x] Create a user friendly report after fixed queries execution
- **Tests**
 - [x] Add JUnit tests for the benchmark suite

- **Data**
 - [x] Select date set to execute benchmack
-  [x] Create corresponding YAML config file

......
