### ISSUE TITLE
Support read/write to standard input/output when indexing a variants file

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#926]
The requirement is to be able to index a file reading directly from the standard-input, and writing the intermediate file in the standard-output.

### Read from STDIN
There are two steps where we read a file, transform and load.

#### Transform
Apart from the file from the standard input, we still need the name of the file. 

#### Load
Apart from the json/avro file from the standard input, we still need the name of the file and the location of the file metadata

### Write to STDOUT
This will only apply to the transform step. This step generates up to 3 files:  
 - `<inputFileName>.variants.avro.gz` Variant file
 - `<inputFileName>.file.json.gz` Variant file metadata
 - `<inputFileName>.malformed.txt` Optional, only to report malformed variants

The variants file will be written to the standard output, while the metadata and the malformed files will still be written to the file system in the output folder.

### Command line
Two new flag arguments will be added:
  - `--stdin` Indicate that the input file should be read from the standard input. 
       Argument `--input` or `--file` is still required.
  - `--stdout` Indicate that the output file should be written to the standard output
       Argument `--output` will still be used to write the metadata file.

##### Transform reading and writing from S3
```bash
aws s3 cp s3://myBucket/myFile.vcf.gz - |
     gzip |
    ./opencga-storage.sh variant index \
            --transform \
            --input myFile.vcf.gz \
            --stdin \
            --outdir /data/ \
            --stdout |
     aws s3 cp - s3://myBucket/myFile.vcf.gz.variants.avro.gz
```

##### Load reading from S3
```bash
aws s3 cp s3://myBucket/myFile.vcf.gz.variants.avro.gz - |
    ./opencga-storage.sh variant index \
            --load \
            --input /data/myFile.vcf.gz.file.json.gz \
            --stdin
```

### Limitations
 - Only one file can be provided at the same time.
 - Can not transform and load in the same command line
 - Can not connect a transform pipeline with a load pipeline, as the metadata file is generated at the end of the transform step.

This behaviour is not intended to change.

### Tasks
 - [x] Read from stdin when transforming
 - [x] Write to stdout when transforming
 - [x] Read from stdin when loading
 - [x] Ensure limitations are checked in preTransform and preLoad 
 - [x] Add new parameters to command line
