### ISSUE TITLE
Create ARM for Solr Cluster

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#938]
Clustered 2 nodes behind internal LB in VNet

#### Tasks
- [x] Create 3 small VMs with Zookeeper
  - [x] Configure zookeepers to know each other
- [x] Create 2 VMs with Solr within the same AvailabilitySet
  - [x] Configure zookeepers location
  - [x] Register OpenCGA ConfigSet
- [x] Register Solr resource in root arm template
