### ISSUE TITLE
Add annotation indexes to the SampleIndex 

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#992]
Currently we can use Solr to filter by any annotation field, and the SampleIndex to filter by any genotype(s). Unfortunately, performance is not as good as desired when we try to filter by both sets of filters at the same time. It would be ideal if we could make some filters from the variant annotation using the SampleIndex table.

#### Proposal

We want to be able to perform partial filters using an annotation "summary". With one byte per variant, we can pre-compute up to 8 filters (one per bit). Then, if the query to execute contains any filter (filtering equal or more restrictively), the filter can be solved with a bitwise operation.

| Bit | Filter | Description |
|---|---|--|
| 0 | Biotype  \* | protein_coding, nonsense_mediated_decay, ...  |
| 1 | PopFreq | PopFreq ALL from 1000G or GNOMAD_GENOMES < 0.001 |
| 2 | Extended Lost of function \*\*  + protein_coding | 
| 3 | Extended Lost of function |
| 4 | Lost of function \*\*\* |
| 5 | Clinical | Any trait association | 
| 6 | Extended Lost of function + basic |
| 7 | n/a |

\* ig_c_gene, ig_d_gene, ig_j_gene, ig_v_gene, protein_coding, nonsense_mediated_decay, non_stop_decay, tr_c_gene, tr_d_gene, tr_j_gene, tr_v_gene
\*\* LoF + missense_variant
 \*\*\* frameshift_variant, inframe_deletion, inframe_insertion, start_lost, stop_gained, stop_lost, splice_acceptor_variant, splice_donor_variant, transcript_ablation, transcript_amplification, initiator_codon_variant, splice_region_variant, incomplete_terminal_codon_variant

#### Indexation process
While loading the annotation, these byte mask should be written also in a new table. Then, use this table to add a new column per genotype in the SampleIndex table, with one byte per variant, in the same order as the variants in the genotype column.

#### Query and filter
These filters will be only possible to use if the given query to execute is filtering equal or more restrictively. 

In case of having a more restrictive filter, it will be finished and validated with the variants table. This will be a pre-filtering only.

For example:
- `popFreq GNOMAD_GENOMES < 0.0001` is more restrictive  than `popFreq GNOMAD_GENOMES < 0.001`, so we can use this filter and use the mask `0b00000010`
- `ct missense_variant OR synonymous_variant ` will return more results than the CT filter, so we can not use it. Mask : `0b00000000`

#### Tasks
- [x] Define a AnnotationIndex converter
- [x] Add AnnotationIndexDBAdaptor with queries methods to scan the table
- [x] Add process to create the new **AnnotationIndex table**
    - [x] Create a MapReduce task to regenerate the Annotation Index table
- [x] Add a new operation to update the SampleIndex table with the information of the AnnotationIndex table.
    - [x] Load only new annotated files
    - <strike> [ ] Add this operation to the command line</strike> #1282 
- [x] Build the annotation index mask given a Query
- [x] Filter variants from the SampleIndex table given a annotation index mask.
- [x] Write down which files have been fully annotated and all their SampleIndexes are updated.
- [ ] Invalidate annotation index after changing the annotation version
