### ISSUE TITLE
Allow the storage metadata scale

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#993]
Currently, the StudyConfiguration holds most of the metadata information from the study. This object has been really useful, but eventually it will become too big to be manageable, and some databases may fail storing it as a single entry.

Instead of using a centralized object that holds all the metadata from a study, we should distribute that, and execute all the queries and updates through an API in the StudyConfigurationManager (or StorageMetadataManager)

### Tasks
- [x] Create new metadata objects and methods
   - [x] storage-mongodb
   - [x] storage-hadoop
- [x] Fix index pipeline
   - [x] storage-mongodb
   - [x] storage-hadoop
- [x] Fix parse query
- [x] Fix converters
   - [x] storage-mongodb
   - [x] storage-hadoop
- [x] Fix other operations
- [x] Improve performance
- [x] Ensure all tests are working
